spring:
  #  jackson:
  #    date-format: yyyy-MM-dd HH:mm:ss.SSS
  #    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?user=root&password=root&useUnicode=true&characterEncoding=utf-8
  #    url: jdbc:h2:mem:manager;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
  activemq:
    broker-url: tcp://127.0.0.1:61616
  jms:
    pub-sub-domain: true
#    generate-ddl: true
#    hibernate:
#    ddl-auto: create-drop
server:
  servlet:
    context-path: /manager
  port: 8081

swagger2:
  enable: true
  groupName: manager
  basePackage: com.imooc.manager.controller

logging:
  level:
    com.googlecode.jsonrpc4j: debug